apiVersion: v1
kind: Service
metadata:
  name: sparrow-platform-service
  labels:
    app: sparrow-platform
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: sparrow-platform-port
      targetPort: 80
      protocol: TCP
  selector:
    app: sparrow-platform
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparrow-platform-deploy
  namespace: default
spec:
  selector:
    matchLabels:
      app: sparrow-platform
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sparrow-platform
    spec:
      containers:
        - image: laozhangisphi/sparrow-platform:latest
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "dev"
          - name: AZURE_TENANT_ID
            valueFrom:
              secretKeyRef:
                name: sparrow-secret
                key: vault-tenant-id
          - name: AZURE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: sparrow-secret
                key: vault-client-id
          - name: AZURE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: sparrow-secret
                key: vault-secret
          - name: AZURE_KEY_VAULT_URI
            value: "https://laozhangisphi.vault.azure.cn/"
          name: sparrow-platform
          ports:
            - containerPort: 80
      imagePullSecrets:
      - name: registry-sparrow-platform
   